### ISSUE TITLE
Ошибка в документации

### ISSUE THREAD

**Issue by profyverya** [AntonMeep/vaniton#1]
В TON невозможно сгенерировать адрес, третьим символом которого будет не A, B, C или D. Соответственно, генерировать адреса командой, которая приведена ниже и любой подобной ей бессмысленно. (команда взята из примеров в README.md)
`vaniton ..ual[i1]z[e3]r.*`

**Comment by AntonMeep** [comment]
Зоркий глаз! Благодарю за репорт, исправлю в ближайшее время.
